# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-29 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LASTIDAPP', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='nextids',
            new_name='nextid',
        ),
        migrations.RenameField(
            model_name='nextid',
            old_name='nextids_id',
            new_name='nextid_id',
        ),
        migrations.RenameField(
            model_name='nextid',
            old_name='nextids_time',
            new_name='nextid_time',
        ),
    ]
